### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by rmalenko** [DennyZhang/devops_public#3]
Hi,
Thank you for plugins
I had met this error 

check_out_of_memory.py: line 25: syntax error near unexpected token `('

**Comment by ArthurChang01** [comment]
Hi,
Thanks for your job!
I search GUI testing on google and I get your blog: http://www.dennyzhang.com/selenium_docker/
I pulled your docker image(denny/selenium) and python source code, when I execute commands that follow by your blog, docker container runs correctly, but I get python's error message as below:

File "selenium_load_page.py", line 87, in <module>
    type=bool)
  File "/usr/lib/python2.7/argparse.py", line 1294, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'type'

**Comment by dennyzhang** [comment]
@rmalenko , could you check this:?
https://github.com/DennyZhang/monitoring/blob/master/os/check_out_of_memory/check_out_of_memory.py

**Comment by dennyzhang** [comment]
@ArthurChang01 : could you try again? Yes, it was a bug which should have been fixed.
